
apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::315949462026:role/eksctl-roboshop-nodegroup-roboshop-NodeInstanceRole-s8LxwXNRBeUJ
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::315949462026:user/dinesh
      username: dinesh
   
kind: ConfigMap
metadata:
  creationTimestamp: "2026-03-12T01:52:39Z"
  name: aws-auth
  namespace: kube-system
  uid: 874ea940-2ec0-44b5-821c-0ea451c217a6

